CREATE ROLE northwind_readonly WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOLOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;
GRANT SELECT ON ALL TABLES IN SCHEMA dbt_dev TO northwind_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO northwind_readonly;
GRANT USAGE ON SCHEMA dbt_dev TO northwind_readonly;
GRANT USAGE ON SCHEMA public TO northwind_readonly;

CREATE ROLE northwind_dbt WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOLOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbt_dev TO northwind_dbt;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO northwind_dbt;
GRANT USAGE ON SCHEMA dbt_dev TO northwind_dbt;
GRANT USAGE ON SCHEMA public TO northwind_dbt;

CREATE USER analyste_dbt WITH PASSWORD 'analyste123';
GRANT northwind_readonly TO analyste_dbt;

CREATE USER dbt_user WITH PASSWORD 'dbt123';
GRANT northwind_dbt TO dbt_user;