services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./data/tmp:/home/jovyan/work/data/tmp
    environment:
      # Make Spark store managed tables in the persisted warehouse directory
      - SPARK_OPTS=--conf spark.sql.warehouse.dir=/home/jovyan/work/data

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
